-- missileburn
-- electricburn
-- burn
-- burnold
-- burnblack
-- burngreen

return {
  ["missileburn"] = {
    groundflash = {
      circlealpha        = 0.1,
      circlegrowth       = 3,
      flashalpha         = 1,
      flashsize          = 12,
      ttl                = 8,
      color = {
        [1]  = 0.80000001192093,
        [2]  = 0.10000000149012,
        [3]  = 0,
      },
    },
    searingflame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.9 0.5 0.4 0.04   0.9 0.4 0.1 0.01  0.5 0.1 0.1 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0.5, 0.5, 0.5]],
        gravity            = [[0, 2, 0]],
        numparticles       = 10,
        particlelife       = 10,
        particlelifespread = 5,
        particlesize       = 20,
        particlesizespread = 0,
        particlespeed      = 5,
        particlespeedspread = 15,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 0.5,
        texture            = [[gunshot]],
        useairlos          = false,
      },
    },
  },

  ["gausscannonprojectile"] = {
        groundflash_small = {
      class              = [[CSimpleGroundFlash]],
      count              = 1,
      air                = true,
      ground             = true,
      water              = true,
      properties = {
        colormap           = [[1 0.7 0.3 0.32   0 0 0 0.01]],
        size               = 25,
        sizegrowth         = -0.5,
        ttl                = 14,
        texture            = [[groundflash]],
      },
    },
    groundflash_large = {
      class              = [[CSimpleGroundFlash]],
      count              = 1,
      air                = true,
      ground             = true,
      water              = true,
      properties = {
        colormap           = [[1 0.7 0.3 0.11   0 0 0 0.01]],
        size               = 50,
        sizegrowth         = -0.5,
        ttl                = 14,
        texture            = [[groundflash]],
      },
    },
    groundflash_white = {
      class              = [[CSimpleGroundFlash]],
      count              = 1,
      air                = true,
      ground             = true,
      water              = true,
      properties = {
        colormap           = [[1 0.9 0.75 0.55   0 0 0 0.01]],
        size               = 41,
        sizegrowth         = 0,
        ttl                = 3,
        texture            = [[groundflash]],
      },
    },
    centerflare = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater         = true,
      properties = {
        heat               = 7,
        heatfalloff        = 1.2,
        maxheat            = 16,
        pos                = [[r-2 r2, 5, r-2 r2]],
        size               = 2,
        sizegrowth         = 6,
        speed              = [[0, 1 0, 0]],
        texture            = [[flare]],
      },
    },
    explosion = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater         = false,
      properties = {
        airdrag            = 0.77,
        colormap           = [[0 0 0 0   1 0.9 0.6 0.09   0.9 0.5 0.2 0.066   0.66 0.28 0.04 0.033   0 0 0 0]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 6,
        particlelife       = 6,
        particlelifespread = 5,
        particlesize       = 1.44,
        particlesizespread = 2.2,
        particlespeed      = 0.3,
        particlespeedspread = 2.5,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.1,
        texture            = [[flashside2]],
        useairlos          = false,
      },
    },
    dustparticles = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = true,
      water              = true,
      properties = {
        airdrag            = 0.88,
        colormap           = [[1 0.85 0.6 0.22  1 0.63 0.3 0.12  1 0.52 0.2 0.06   0 0 0 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0.5, 1, 0.5]],
        gravity            = [[0, -0.011, 0]],
        numparticles       = 2,
        particlelife       = 4,
        particlelifespread = 2,
        particlesize       = 2.5,
        particlesizespread = 0.66,
        particlespeed      = 0.55,
        particlespeedspread = 0.2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2.2,
        sizemod            = 1.0,
        texture            = [[randomdots]],
      },
    },
    innersmoke = {
      class = [[CSimpleParticleSystem]],
      water=0,
      air=1,
      ground=1,
      count=1,
      properties = {
        airdrag=0.8,
        alwaysVisible = 0,
        sizeGrowth = 0.4,
        sizeMod = 1,
        pos = [[r-1 r1, 0, r-1 r1]],
        emitRot=35,
        emitRotSpread=40,
        emitVector = [[0, 1, 0]],
        gravity = [[0, 0.014, 0]],
        colormap=[[1 0.66 0.4 0.45    0.3 0.2 0.13 0.4   0.18 0.15 0.11 0.35    0.13 0.12 0.1 0.32   0.11 0.1 0.093 0.25   0.063 0.062 0.058 0.17    0 0 0 0.01]],
        Texture=[[graysmoke]],
        particleLife=22,
        particleLifeSpread=45,
        numparticles=2,
        particleSpeed=0.6,
        particleSpeedSpread=2.7,
        particleSize=4,
        particleSizeSpread=2.5,
        directional=0,
      },
    },
    outersmoke = {
      class = [[CSimpleParticleSystem]],
      water=0,
      air=1,
      ground=1,
      count=1,
      properties = {
        airdrag=0.4,
        alwaysVisible = 0,
        sizeGrowth = 0.35,
        sizeMod = 1.0,
        pos = [[r-1 r1, 0, r-1 r1]],
        emitRot=33,
        emitRotSpread=50,
        emitVector = [[0, 1, 0]],
        gravity = [[0, -0.02, 0]],
        colormap=[[1 0.66 0.4 0.45    0.3 0.2 0.13 0.4   0.18 0.15 0.11 0.35    0.13 0.12 0.1 0.32   0.11 0.1 0.093 0.25   0.063 0.062 0.058 0.17    0 0 0 0.01]],
        Texture=[[graysmoke]],
        particleLife=15,
        particleLifeSpread=25,
        numparticles=2,
        particleSpeed=1,
        particleSpeedSpread=3.3,
        particleSize=7.5,
        particleSizeSpread=2.5,
        directional=0,
      },
    },
    dirt = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = false,
      air                = false,
      ground             = true,
      unit               = false,
      nounit             = true,
      underwater         = false,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.01 0   0.1 0.07 0.033 0.66   0.1 0.07 0.033 0.58   0.1 0.07 0.033 0.5   0.1 0.07 0.033 0.4   0 0 0 0  ]],
        directional        = true,
        emitrot            = 22,
        emitrotspread      = 40,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.3, 0]],
        numparticles       = 2,
        particlelife       = 16,
        particlelifespread = 4,
        particlesize       = 1.2,
        particlesizespread = -1,
        particlespeed      = 1.4,
        particlespeedspread = 1.75,
        pos                = [[0, 4, 0]],
        sizegrowth         = -0.01,
        sizemod            = 1,
        texture            = [[bigexplosmoke]],
        useairlos          = false,
      },
    },
    dirt2 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = false,
      air                = false,
      ground             = false,
      unit               = false,
      nounit             = true,
      underwater         = false,
      properties = {
        airdrag            = 1,
        colormap           = [[0.04 0.03 0.01 0   0.1 0.07 0.033 0.66   0.1 0.07 0.033 0.58   0.1 0.07 0.033 0.5   0.1 0.07 0.033 0.4   0 0 0 0  ]],
        directional        = true,
        emitrot            = -5,
        emitrotspread      = 11,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.3, 0]],
        numparticles       = 2,
        particlelife       = 18,
        particlelifespread = 4,
        particlesize       = 1.23,
        particlesizespread = -1,
        particlespeed      = 1.66,
        particlespeedspread = 2.4,
        pos                = [[0, 4, 0]],
        sizegrowth         = -0.01,
        sizemod            = 1,
        texture            = [[bigexplosmoke]],
        useairlos          = false,
      },
    },
    clouddust = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.91,
        colormap           = [[0 0 0 0.01   0.025 0.025 0.025 0.035  0.06 0.06 0.06 0.08  0.05 0.05 0.05 0.065  0.026 0.026 0.026 0.035  0 0 0 0.01]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 4,
        emitvector         = [[0.25, 0.8, 0.25]],
        gravity            = [[0, 0.015, 0]],
        numparticles       = 1,
        particlelife       = 33,
        particlelifespread = 55,
        particlesize       = 5,
        particlesizespread = 8,
        particlespeed      = 0.5,
        particlespeedspread = 1.5,
        pos                = [[0, 6, 0]],
        sizegrowth         = 0.1,
        sizemod            = 1.0,
        texture            = [[bigexplosmoke]],
      },
    },
    --grounddust = {
    --  air                = false,
    --  class              = [[CSimpleParticleSystem]],
    --  count              = 1,
    --  ground             = true,
    --  unit               = false,
    --  properties = {
    --    airdrag            = 0.86,
    --    colormap           = [[0.07 0.07 0.07 0.1     0 0 0 0.0]],
    --    directional        = true,
    --    emitrot            = 90,
    --    emitrotspread      = -2,
    --    emitvector         = [[0, 1, 0]],
    --    gravity            = [[0, 0.02, 0]],
    --    numparticles       = 12,
    --    particlelife       = 10,
    --    particlelifespread = 40,
    --    particlesize       = 3,
    --    particlesizespread = 2,
    --    particlespeed      = 2.2,
    --    particlespeedspread = 0.8,
    --    pos                = [[0, 1, 0]],
    --    sizegrowth         = 0.1,
    --    sizemod            = 1.0,
    --    texture            = [[bigexplosmoke]],
    --  },
    --},
    shard1 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      unit                = true,
      nounit              = false,
      underwater          = false,
      properties = {
        airdrag            = 0.93,
        colormap           = [[1 0.55 0.45 1    0.55 0.44 0.38 1    0.36 0.34 0.33 1    0 0 0 0.01]],
        directional        = true,
        emitrot            = 35,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.3, 0]],
        numparticles       = [[1 r1.2]],
        particlelife       = 28,
        particlelifespread = 0,
        particlesize       = 1.1,
        particlesizespread = 1.8,
        particlespeed      = 1.35,
        particlespeedspread = 2.65,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[shard1]],
        useairlos          = false,
      },
    },
    shard2 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      unit                = true,
      nounit              = false,
      underwater          = false,
      properties = {
        airdrag            = 0.93,
        colormap           = [[1 0.55 0.45 1    0.55 0.44 0.38 1    0.36 0.34 0.33 1    0 0 0 0.01]],
        directional        = true,
        emitrot            = 35,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.3, 0]],
        numparticles       = [[0 r1.6]],
        particlelife       = 28,
        particlelifespread = 0,
        particlesize       = 1.3,
        particlesizespread = 1.6,
        particlespeed      = 1.35,
        particlespeedspread = 2.65,
        pos                = [[1, 2, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[shard2]],
        useairlos          = false,
      },
    },
    shard3 = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      unit                = true,
      nounit              = false,
      underwater          = false,
      properties = {
        airdrag            = 0.93,
        colormap           = [[1 0.55 0.45 1    0.55 0.44 0.38 1    0.36 0.34 0.33 1    0 0 0 0.01]],
        directional        = true,
        emitrot            = 35,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.3, 0]],
        numparticles       = [[0 r1.6]],
        particlelife       = 28,
        particlelifespread = 0,
        particlesize       = 1.8,
        particlesizespread = 2,
        particlespeed      = 1.35,
        particlespeedspread = 1.65,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[shard3]],
        useairlos          = false,
      },
    },
    sparks = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater         = false,
      properties = {
        airdrag            = 0.94,
        colormap           = [[0.9 0.85 0.77 0.017   0.8 0.55 0.3 0.011   0 0 0 0]],
        directional        = true,
        emitrot            = 30,
        emitrotspread      = 35,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.15, 0]],
        numparticles       = 2,
        particlelife       = 10,
        particlelifespread = 8,
        particlesize       = 17,
        particlesizespread = 14,
        particlespeed      = 4.75,
        particlespeedspread = 3,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.77,
        sizemod            = 0.7,
        texture            = [[gunshotglow]],
        useairlos          = false,
      },
    },
    outerflash = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater         = true,
      properties = {
        heat               = 7,
        heatfalloff        = 1.5,
        maxheat            = 15,
        pos                = [[r-2 r2, 5, r-2 r2]],
        size               = 4,
        sizegrowth         = 0.6,
        speed              = [[0, 1 0, 0]],
        texture            = [[orangenovaexplo]],
      },
    },
    },
  ["electricburn"] = {
    groundflash = {
      circlealpha        = 0.1,
      circlegrowth       = 3,
      flashalpha         = 1,
      flashsize          = 12,
      ttl                = 8,
      color = {
        [1]  = 0,
        [2]  = 0.10000000149012,
        [3]  = 0.80000001192093,
      },
    },
    searingflame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.4 0.5 0.9 0.04   0.1 0.4 0.9 0.01  0.1 0.1 0.5 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 2,
        particlelife       = 10,
        particlelifespread = 5,
        particlesize       = 20,
        particlesizespread = 0,
        particlespeed      = 5,
        particlespeedspread = 5,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 0.5,
        texture            = [[gunshot]],
        useairlos          = false,
      },
    },
    smokeandfire = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.70,
        colormap           = [[0.1 0.1 0.1 0.01    0.0 0.3 0.5 0.05    0.1 0.1 0.5 1.0    0.1 0.1 0.1 1.0    0.5 0.5 0.5 1.0   0 0 0 0.01]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0.0, 1, 0.0]],
        gravity            = [[0.0, 2, 0.0]],
        numparticles       = 3,
        particlelife       = 10,
        particlelifespread = 4,
        particlesize       = 0,
        particlesizespread = 5,
        particlespeed      = 0,
        particlespeedspread = 2,
        pos                = [[0.0, 1, 0.0]],
        sizegrowth         = 3,
        sizemod            = 0.5,
        texture            = [[dirt]],
        useairlos          = true,
      },
    },
  },

  ["burnold"] = {
    groundflash = {
      circlealpha        = 0.1,
      circlegrowth       = 3,
      flashalpha         = 1,
      flashsize          = 12,
      ttl                = 8,
      color = {
        [1]  = 0.80000001192093,
        [2]  = 0.10000000149012,
        [3]  = 0,
      },
    },
    searingflame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.9 0.5 0.4 0.04   0.9 0.4 0.1 0.01  0.5 0.1 0.1 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 2, 0]],
        numparticles       = 10,
        particlelife       = 10,
        particlelifespread = 5,
        particlesize       = 20,
        particlesizespread = 0,
        particlespeed      = 5,
        particlespeedspread = 15,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 0.5,
        texture            = [[gunshot]],
        useairlos          = false,
      },
    },
    smokeandfire = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.70,
        colormap           = [[0.1 0.1 0.1 0.01    0.5 0.3 0.0 0.05    0.5 0.1 0.1 1.0    0.1 0.1 0.1 1.0    0.5 0.5 0.5 1.0   0 0 0 0.01]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0.0, 1, 0.0]],
        gravity            = [[0.0, 2, 0.0]],
        numparticles       = 3,
        particlelife       = 10,
        particlelifespread = 4,
        particlesize       = 0,
        particlesizespread = 5,
        particlespeed      = 0,
        particlespeedspread = 2,
        pos                = [[0.0, 1, 0.0]],
        sizegrowth         = 3,
        sizemod            = 0.5,
        texture            = [[dirt]],
        useairlos          = true,
      },
    },
  },

  ["pilotlight"] = {
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.55,
        colormap           = [[1 0.95 0.66 0.01   0.65 0.45 0.15 0.01   0.3 0.18 0.02 0.01  0 0 0 0.01]],
        directional        = true,
        emitrot            = 5,
        emitrotspread      = 22,
        emitvector         = [[dir]],
        gravity            = [[0, 0.35, 0]],
        numparticles       = 1,
        particlelife       = 4.5,
        particlelifespread = 2,
        particlesize       = 1.2,
        particlesizespread = 0.8,
        particlespeed      = 1.4,
        particlespeedspread = 3.5,
        pos                = [[-0.5 r1, 1, -0.5 r1]],
        sizegrowth         = 0.9,
        sizemod            = 1.0,
        texture            = [[flame]],
        useairlos          = false,
      },
    },
  },

  ["burnblack"] = {
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.9 0.9 0.9 0.3  0.7 0.7 0.7 0.2   0.1 0.1 0.1 0.11   0 0 0 0.08   0 0 0 0.05   0 0 0 0.03   0 0 0 0.01]],
        directional        = true,
        emitrot            = 70,
        emitrotspread      = 40,
        emitvector         = [[0.3, 1, 0.3]],
        gravity            = [[0, 0.11, 0]],
        numparticles       = 1,
        particlelife       = 18,
        particlelifespread = 32,
        particlesize       = 14,
        particlesizespread = 12,
        particlespeed      = 0.5,
        particlespeedspread = 0.7,
        pos                = [[-3 r6, -3 r6, -3 r6]],
        sizegrowth         = 0.6,
        sizemod            = 0.99,
        texture            = [[fire]],
      },
    },
  },

  ["burnblackbig"] = {
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.91 0.9 0.9 0.3  0.72 0.7 0.7 0.2   0.12 0.11 0.1 0.11   0 0 0 0.08   0 0 0 0.05   0 0 0 0.03   0 0 0 0.01]],
        directional        = true,
        emitrot            = 65,
        emitrotspread      = 65,
        emitvector         = [[0.3, 1, 0.3]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 3,
        particlelife       = 40,
        particlelifespread = 36,
        particlesize       = 10,
        particlesizespread = 12,
        particlespeed      = 0.45,
        particlespeedspread = 0.4,
        pos                = [[-3 r6, -3 r6, -3 r6]],
        sizegrowth         = 0.7,
        sizemod            = 0.98,
        texture            = [[fire]],
      },
    },
  },

  ["burnblackbiggest"] = {
    particles = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.7 0.3 1.0 0.8  0.2 0.1 0.80 0.2   0.10 0.03 0.20 0.11   0.01 0 0.02 0.08   0.01 0 0.020 0.05   0.01 0 0.02 0.01]],
        directional        = true,
        emitrot            = 65,
        emitrotspread      = 65,
        emitvector         = [[0.3, 1, 0.3]],
        gravity            = [[0, 0.09, 0]],
        numparticles       = 4,
        particlelife       = 60,
        particlelifespread = 66,
        particlesize       = 13,
        particlesizespread = 15,
        particlespeed      = 0.45,
        particlespeedspread = 0.4,
        pos                = [[-3 r6, -3 r6, -3 r6]],
        sizegrowth         = 0.7,
        sizemod            = 0.99,
        texture            = [[randdots]],
      },
    },
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.01 0 0.02 0.01   0.7 0.3 1.0 0.8  0.2 0.1 0.80 0.2   0.10 0.03 0.20 0.11   0.01 0 0.02 0.08   0.01 0 0.020 0.05   0.01 0 0.02 0.01]],
        directional        = true,
        emitrot            = 65,
        emitrotspread      = 65,
        emitvector         = [[0.3, 1, 0.3]],
        gravity            = [[0, 0.00, 0]],
        numparticles       = 4,
        particlelife       = 60,
        particlelifespread = 66,
        particlesize       = 13,
        particlesizespread = 15,
        particlespeed      = 0.45,
        particlespeedspread = 0.4,
        pos                = [[-3 r6, -3 r6, -3 r6]],
        sizegrowth         = 0.7,
        sizemod            = 0.99,
        texture            = [[smoke_puff]],
      },
    },
  },

  ["burngreen"] = {
    groundflash = {
      circlealpha        = 0.1,
      circlegrowth       = 3,
      flashalpha         = 1,
      flashsize          = 12,
      ttl                = 8,
      color = {
        [1]  = 0.80000001192093,
        [2]  = 0.10000000149012,
        [3]  = 0,
      },
    },
    searingflame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.4 0.9 0.4 0.04   0.4 0.9 0.1 0.01  0.1 0.5 0.1 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0.5, 0.5, 0.5]],
        gravity            = [[0, 2, 0]],
        numparticles       = 10,
        particlelife       = 10,
        particlelifespread = 5,
        particlesize       = 20,
        particlesizespread = 0,
        particlespeed      = 5,
        particlespeedspread = 15,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 0.5,
        texture            = [[gunshot]],
        useairlos          = false,
      },
    },
    smokeandfire = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.70,
        colormap           = [[0.1 0.1 0.1 0.01    0.0 0.5 0.0 0.05    0.1 0.5 0.1 1.0    0.1 0.1 0.1 1.0    0.5 0.5 0.5 1.0   0 0 0 0.01]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[1, 1, 1]],
        gravity            = [[0.0, 2, 0.0]],
        numparticles       = 3,
        particlelife       = 10,
        particlelifespread = 4,
        particlesize       = 0,
        particlesizespread = 5,
        particlespeed      = 0,
        particlespeedspread = 2,
        pos                = [[0.0, 1, 0.0]],
        sizegrowth         = 3,
        sizemod            = 0.5,
        texture            = [[dirt]],
        useairlos          = true,
      },
    },
  },
  	 ["flamerceg"] = {
    fire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
	 colormap           = [[0.7 0.7 0.7 0.01  1 0.5 0.5 0.5   0 0 0 0]],
	 directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[dir]],
          gravity            = [[0.15 r-0.3, 0.2 r-0.3, 0.15 r-0.3]],
        numparticles       = 1,
        particlelife       = 5,
        particlelifespread = 3,
        particlesize       = 3,
        particlesizespread = 8,
        particlespeed      = 0.1,
        particlespeedspread = 0.1,
        pos                = [[6 r-12, 6 r-12, 6 r-12]],
       sizegrowth         = 0.7,
        sizemod            = 1.0,
        texture            = [[flame]],
      },
    },
  },
  
  ["flamerexplode"] = {
    fire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.7 0.7 0.7 0.01  1 0.5 0.5 0.5   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[dir]],
        gravity            = [[0.15 r-0.3, 0.2 r-0.3, 0.15 r-0.3]],
        numparticles       = 1,
        particlelife       = 8,
        particlelifespread = 5,
        particlesize       = 8,
        particlesizespread = 4,
        particlespeed      = 0.1,
        particlespeedspread = 0.1,
        pos                = [[6 r-12, 6 r-12, 6 r-12]],
        sizegrowth         = 0.7,
        sizemod            = 1.0,
        texture            = [[flame]],
      },
    },
  },
  
   ["dgunfx"] = {
  groundflash_large = {
            class              = [[CSimpleGroundFlash]],
            count              = 1,
            air                = true,
            ground             = true,
            water              = true,
            properties = {
                colormap           = [[1 0.7 0.3 0.04   0 0 0 0.01]],
                size               = 65,
                sizegrowth         = -0.5,
                ttl                = 14,
                texture            = [[groundflash]],
            },
        },
          brightflare = {
          air                = true,
          class              = [[CBitmapMuzzleFlame]],
          count              = 1,
          ground             = true,
          underwater         = true,
          water              = true,
          properties = {
            colormap           = [[0.65 0.25 0.15 0.2    0 0 0 0.1]],
            dir                = [[0, 0, 0]],
            --gravity            = [[0.0, 0.1, 0.0]],
            frontoffset        = 0,
            fronttexture       = [[dirt]],
            length             = 40,
            sidetexture        = [[none]],
            size               = [[40 r20]],
            sizegrowth         = -0.3,
            ttl                = 2,
            pos                = [[0, 0, 0]],
            --rotParams          = [[-10 r20, -20 r40, -180 r360]],
          },
        },
        ball = {
            air                = true,
            class              = [[CSimpleParticleSystem]],
            count              = 1,
            ground             = true,
            underwater         = true,
            water              = true,
            properties = {
                airdrag            = 0.4,
                colormap           = [[0.75 0.60 0.55 0.05   0.70 0.58 0.50 0.15   0.21 0.15 0.14 0.1   0 0 0 0.01]],
                directional        = false,
                emitrot            = 45,
                emitrotspread      = 32,
                emitvector         = [[0, 1, 0]],
                gravity            = [[0, -0.05, 0]],
                numparticles       = 4,
                particlelife       = 10,
                particlelifespread = 2,
                particlesize       = 10,
                particlesizespread = 2,
                particlespeed      = 0.5,
                particlespeedspread = 2.9,
                pos                = [[0, 2, 0]],
                sizegrowth         = -0.3,
                sizemod            = 1.0,
                texture            = [[dirt]],
                useairlos          = false,
            },
        },
    },
}

