-- com_explo
return {
  ["com_explo"] = {
     usedefaultexplosions = false,

      smokecloud = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1, --1
      ground             = true,
      underwater         = 0,
      water              = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.1 0.1 0.1 0.4		0.1 0.1 0.1 0.3		0.1 0.1 0.1 0.2		0.1 0.1 0.1 0.2	 0 0 0 0.00]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 360,
        emitvector         = [[0,1,0]],
        gravity            = [[0 , 0.0012, 0]],
        numparticles       = 150,
        particlelife       = 140,
        particlelifespread = 120,
        particlesize       = 30,
        particlesizespread = 25,
        particlespeed      = [[2 i0.25]],
        particlespeedspread = 2.2,
        pos                = [[-13 r13,-13 r13,-13 r13]],
        sizegrowth         = -0.35,
        sizemod            = 1.0,
        texture            = [[smoke]],
        useairlos          = true,
      },
    },
      smokecloud1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1, --1
      ground             = true,
      underwater         = 0,
      water              = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.1 0.1 0.1 0.4		0.1 0.1 0.1 0.3		0.1 0.1 0.1 0.2		0.1 0.1 0.1 0.2	 0 0 0 0.00]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 360,
        emitvector         = [[0,1,0]],
        gravity            = [[0 , 0.0012, 0]],
        numparticles       = 100,
        particlelife       = 170,
        particlelifespread = 120,
        particlesize       = 20,
        particlesizespread = 25,
        particlespeed      = [[2 i0.25]],
        particlespeedspread = 2.2,
        pos                = [[-3 r3,-3 r3,-3 r3]],
        sizegrowth         = -0.35,
        sizemod            = 1.0,
        texture            = [[smoke]],
        useairlos          = true,
      },
    },
       smokecloud2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1, --1
      ground             = true,
      underwater         = 0,
      water              = true,
      properties = {
        airdrag            = 0.99,
        colormap           = [[0.1 0.1 0.1 0.4		0.1 0.1 0.1 0.3		0.1 0.1 0.1 0.2		0.1 0.1 0.1 0.2	 0 0 0 0.00]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 360,
        emitvector         = [[0,1,0]],
        gravity            = [[0 , 0.00000012, 0]],
        numparticles       = 150,
        particlelife       = 170,
        particlelifespread = 120,
        particlesize       = 50,
        particlesizespread = 25,
        particlespeed      = [[2 i0.25]],
        particlespeedspread = 2.2,
        pos                = [[-3 r3,-3 r3,-3 r3]],
        sizegrowth         = -0.35,
        sizemod            = 1.0,
        texture            = [[smoke]],
        useairlos          = true,
      },
    },
      smokering_top = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1, --1
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        airdrag            = 0.99,
        colormap           = [[0 0 0 0.00	0 0 0 0.00	0.1 0.1 0.1 0.3		0.1 0.1 0.1 0.3		0.1 0.1 0.1 0.2		0.1 0.1 0.1 0.2		0 0 0 0.00]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0.001, 0.0072, 0.001]],
        numparticles       = 200,
        particlelife       = 160,
        particlelifespread = 95,
        particlesize       = [[1.2]],
        particlesizespread = 0,
        particlespeed      = [[2.1]],
        particlespeedspread = 1,
        pos                = [[0 , 20, 0]],
        sizegrowth         = [[0.20]],
        sizemod            = 1.0,
        texture            = [[smoke]],
        useairlos          = true,
      },
    },
  },
}


