return {
  ["flashjuno"] = {
    air                = true,
    ground             = true,
    usedefaultexplosions = false,
    water              = true,
    groundflash = {
      circlealpha        = 0.5,
      circlegrowth       = 18,
      flashalpha         = 1.5,
      flashsize          = 500,
      ttl                = 60,
      color = {
        [1]  = 0.7,
        [2]  = 0.9,
        [3]  = 0.55,
      },
    },
      Sparklespawner = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 750,
      ground             = true,
      water              = true,
      properties = {
        delay              = [[0 i0.85 r1]],
        explosiongenerator = [[custom:junosparkle]],
        pos                = [[-300 r600,5, -300 r600]],
    },
  },
   GlowSpawner = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 60,
      ground             = true,
      water              = false,
      properties = {
        delay              = [[0 i14]],
        explosiongenerator = [[custom:Glow3]],
        pos                = [[0, 0, 0]],
      },
    },
  },
    ["Glow3"] = {
     glow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.7 0.9 0.55 0.003    0.7 0.9 0.55 0.003              0 0 0 0.006]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0, 0]],
        gravity            = [[0, 0.00, 0]],
        numparticles       = 1,
        particlelife       = 3,
        particlelifespread = 0,
        particlesize       = 60,
        particlesizespread = 20,
        particlespeed      = 2,
        particlespeedspread = 0,
        pos                = [[0, 2, 0]],
        sizegrowth         = 35.0,
        sizemod            = 1.0,
        texture            = [[flare1]],
      },
    },
    groundflash = {
      circlealpha        = 0.2,
      circlegrowth       = 8,
      flashalpha         = 0.3,
      flashsize          = 64,
      ttl                = 60,
      color = {
        [1]  = 0.7,
        [2]  = 0.9,
        [3]  = 0.55,
      },
    },
  },
  ["junosparkle"] = {
    usedefaultexplosions = false,
    sparkle = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = false,
        colormap           = [[0.7 0.9 0.55 0.01   0.7 0.9 0.55 0.01        0.1 0.1 0.1 0.01]],
        directional        = false,
        emitrot            = [[0 r2]],
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = [[5 i0.43 r1]],
        particlelifespread = 0,
        particlesize       = 5.2,
        particlesizespread = 0,
        particlespeed      = 24,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = -0.98,
        texture            = [[nanoball]],
        useairlos          = false,
      },
    },
   },
}
