return {
	armrecl = {
		acceleration = 0.14,
		autoheal = 2,
		brakerate = 0.075,
		buildcostenergy = 4423,
		buildcostmetal = 418,
		builddistance = 140,
		builder = true,
		buildpic = "ARMRECL.DDS",
		buildtime = 7407,
		canassist = false,
		canmove = true,
		canresurrect = true,
		category = "ALL UNDERWATER NOWEAPON NOTAIR NOTHOVER",
		collisionvolumeoffsets = "0 0 2",
		collisionvolumescales = "38 17 50",
		collisionvolumetype = "box",
		description = "Ressurection Sub",
		explodeas = "smallexplosiongeneric-uw",
		footprintx = 2,
		footprintz = 2,
		icontype = "sea",
		idleautoheal = 3,
		idletime = 300,
		maxdamage = 670,
		maxvelocity = 2.57,
		minwaterdepth = 15,
		movementclass = "UBOAT33X3",
		name = "Grim Reaper",
		objectname = "ARMRECL",
		seismicsignature = 0,
		selfdestructas = "smallexplosiongenericSelfd-uw",
		shownanospray = false,
		sightdistance = 430,
		sonardistance = 270,
		terraformspeed = 2250,
		turninplace = true,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.6962,
		turnrate = 600,
		waterline = 17,
		workertime = 450,
		customparams = {
			subfolder = "armships",
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2-builder",
				[2] = "deathceg3-builder",
				[3] = "deathceg4-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			capture = "capture1",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sucormov",
			},
			select = {
				[1] = "sucorsel",
			},
		},
	},
}
