General = {
 {"Chat", title=true},
    {"enter",                     "Send chat message"},
    {"alt + enter",               "Send chat message to allies"},
    {"shift + enter",             "Send chat message to spectators"},
{blankLine=true}, 

{"Mouse and Orders", title=true},
{"scrollwheel",                 "Zoom camera"},
{"LEFT CLICK",         "Select or deselect units"},
{"LEFT CLICK + space",         "Lasso select units"},
{"LEFT CLICK + ctrl",         "Deselect part of a selection"},
{"RIGHT CLICK",         "Give order to selected units"},
{"RIGHT CLICK + drag",         "Give line formation order to selection"},
{"LEFT CLICK + drag",         "Give circular area order to selection"},
{"RIGHT CLICK + ctrl",         "Do order at the speed of slowest"},
{"order + shift",         "Add order to end of  queue"},
{"order + space",         "Insert order at start of queue"},
{blankLine=true},
 
{"Order Hotkeys", title=true},
{"A",         "Attack"},
{"M",         "Move"},
{"S",         "Stop and cancel current orders"},
{"F",         "Fight while advancing"},
{"D",         "D-gun"},
{"E",         "Reclaim"},
{"R",         "Repair"},
{"W",         "Wait and pause current task"},
{"P",         "Patrol"},
{"G",         "Guard"},
{"L",         "Load"},
{"U",         "Unload"},
{"Q",         "Set target on ground or unit"},
{"ctrl + D",         "Self destruct"},
{"H",   "Share units or resources to allies"},
}

Units_I_II = {
{"Builder Hotkeys", title=true},
{"z",         "Cycle through metal production buildings, anti, sheild"},
    {"x",         "Cycle through energy production buildings"},
    {"c",         "Cycle through ground turrets"},
    {"v",         "Cycle through nano, anti-air, and radar"},
{blankLine=true}, 

{"Unit Hotkeys", title=true},
{"ctrl + C",         "Select commander"},
{"ctrl + A",         "Select all units"},
{"ctrl + Z",         "Select all units that match selection types"},
{"ctrl + X or double left click",        "Select visible unit matches" },
{"ctrl + B",         "Select next idle builder"},
{blankLine=true}, 

{"Unit Control Group Hotkeys", title=true},
{"Press Number",         "Select group"},
{"Double Press Number",         "Center camera on group"},
{"ctrl + Number",         "Add selected unit to group"},
{"` + ctrl + Number",         "Remove selected unit from group"},
{"ALT + Number",         "Add selected unit type to auto group"},
{"` + ALT + Number",     "Remove selected unit type from auto group"},
{blankLine=true},  

{"Construction Hotkeys", title=true},
{"[ or ]",   "Change building direction"},
{"B or N or side mouse",   "+ or - building spacings"},
{"LEFT CLICK + SHIFT + DRAG",   "Build structures in a line"},
{"LEFT CLICK + ctrl + SHIFT + DRAG",   "Build in right angle lines"},
{"LEFT CLICK + alt + SHIFT + DRAG",   "Build structures in a box"},
{"LEFT CLICK + ctrl + alt + SHIFT + DRAG",   "Hollow box"},
{"ANY COMMAND ABOVE + SPACE",   "Split builders between tasks"},
{blankLine=true}, 

{"Spectator Controls", title=true},
{"double click name",         "Track player cam"},
{"cntrl click name",         "Mute player"},
}

Units_III = {
{"Camera and map", title=true},
    {"arrow keys / mouse screen edge", "Move camera"},
    {"ctrl + scrollwheel",          "Change camera angle"},
    {"middle click (+ drag) or J",       "Drag camera"},
    {"tab",                         "Toggle mega map"},
    {"ctrl + shift + o",            "Flip camera"},
	{"L",   "Toggle fog of war"},
	
	{"ctrl + f1,2,3,4,5",           "Change camera type"},
	{"f1",  "Show height map"},
    {"f2",  "Show terrain passability (for selected unit)"},
    {"f3",  "Cycle through map marks"},
    {"f4",  "Show metal map"},
    {"f5",  "Hide GUI"},
	{"f12",  "Screenshot"},
	{blankLine=true}, 
	
 {"Drawing", title=true},
    {"` + double click",       "Place map mark"},
    {"` + drag left mouse", "Draw on map"},
    {"` + drag right mouse","Erase drawings and markers"},
	 {"click on eraser",  "Erase all drawings and markes"},
{blankLine=true}, 

{"Widgets", title=true},
{"f11",  "Widget menu to enable and disable widgets"},
{"ctrl + f11",  "Widget tweak mode"},
{"middle mouse",  "Move selected widget in tweak mode"},
{blankLine=true}, 

{"Sound", title=true},
{"-/+",                 "Change volume"},
{"f6",                  "Toggle mute"},
{blankLine=true}, 

{"Replay", title=true},
{"alt and + or -",  "Speed up or slow down replay"},
}

