return {
    supersimple = {
        buildcostenergy = 1,
        buildcostmetal = 1,
        buildpic = "ARMNANOTC.DDS",
        buildtime = 1,
        cantbetransported = true,
        category = "NOTSUB NOWEAPON NOTAIR",
        collisionvolumeoffsets = "0 -1 0",
        collisionvolumescales = "1 1 1",
        collisionvolumetype = "CylY",
        description = "SuperSimple",
        footprintx = 1,
        footprintz = 1,
        icontype = "building",
        mass = 10000,
        maxdamage = 999999,
        maxslope = 999999,
        maxwaterdepth = 999999,
        name = "SuperSimple",
        objectname = "supersimplemodo.dae",
        script="supersimple.dae.lua",
        sightdistance = 100,
        terraformspeed = 100,
        turnrate = 0,
        sounds = {
            build = "nanlath1",
            canceldestruct = "cancel2",
        },
    },
}
