return {
    techcapture = {
        buildcostenergy = 3222,
        buildcostmetal = 600,
        buildpic = "ARMNANOTC.DDS",
        buildtime = 5312,
        cantbetransported = true,
        category = "NOTSUB NOWEAPON NOTAIR NOTHOVER",
        collisionvolumeoffsets = "0 -1 0",
        collisionvolumescales = "1 1 1",
        collisionvolumetype = "CylY",
        description = "Tech - Capture",
        footprintx = 1,
        footprintz = 1,
        icontype = "building",
        mass = 10000,
        maxdamage = 999999,
        maxslope = 999999,
        maxwaterdepth = 999999,
        name = "Tech - Capture",
        objectname = "armoutpost.dae",
        sightdistance = 0,
        terraformspeed = 0,
        turnrate = 0,
        sounds = {
            build = "nanlath1",
            canceldestruct = "cancel2",
        },
    },
}
