return {
	amgeo = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 0,
		buildcostenergy = 26509,
		buildcostmetal = 1621,
		buildpic = "AMGEO.DDS",
		buildtime = 33152,
		category = "ALL NOTSUB NOWEAPON NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "-2 -2 6",
		collisionvolumescales = "69 69 107",
		collisionvolumetype = "box",
		description = "Hazardous Energy Source",
		energymake = 1250,
		energystorage = 12000,
		explodeas = "geoboom",
		footprintx = 5,
		footprintz = 8,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 3240,
		maxslope = 15,
		maxwaterdepth = 0,
		name = "Moho Geothermal Powerplant",
		objectname = "AMGEO",
		seismicsignature = 0,
		selfdestructas = "geoboom",
		sightdistance = 273,
		usebuildinggrounddecal = false,
		yardmap = "ooooo ooooo ooooo ooooo ooooo oGGGo oGGGo ooooo",
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "geothrm1",
			},
		},
	},
}
