local wreck_metal = 2500
if (Spring.GetModOptions) then
		if (Spring.GetModOptions().comm_wreck_metal) then 
		wreck_metal = Spring.GetModOptions().comm_wreck_metal or 2500
		end
end

return {
	corcom3 = {
		acceleration = 0.18,
		activatewhenbuilt = true,
		autoheal = 5*(4/3)*(4/3),
		brakerate = 1.125,
		buildcostenergy = 26500*(4/3)*(4/3),
		buildcostmetal = 2670*(4/3)*(4/3),
		builddistance = 130*(7/6)*(7/6),
		builder = true,
		shownanospray = false,
		buildpic = "CORCOM.DDS",
		buildtime = 75000*(4/3)*(4/3),
		cancapture = true,
		canmanualfire = true,
		canmove = true,
		capturespeed = 1800*(4/3)*(4/3),
		category = "ALL WEAPON COMMANDER NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE",
		cloakcost = 100*(4/3)*(4/3),
		cloakcostmoving = 1000*(4/3)*(4/3),
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "27 39 27",
		collisionvolumetype = "CylY",
		commander = true,
		corpse = "DEAD",
		description = "Commander",
		energymake = 35*(4/3)*(4/3),
		explodeas = "commanderexplosion",
		footprintx = 2,
		footprintz = 2,
		hidedamage = true,
		icontype = "corcommander",
		idleautoheal = 5*(4/3)*(4/3),
		idletime = 1800,
		losemitheight = 40,
		mass = 5000*(4/3)*(4/3),
		maxdamage = 3000*(4/3)*(4/3),
		maxslope = 20,
		maxvelocity = 1.25*1.025*1.025,
		maxwaterdepth = 35,
		metalmake = 1.5*(4/3)*(4/3),
		mincloakdistance = 50,
		movementclass = "AKBOT2",
		name = "Commander",
		nochasecategory = "ALL",
		objectname = "CORCOMLVL3",
		pushresistant = true,
		radardistance = 700*(11/10)*(11/10),
		radaremitheight = 40,
		reclaimable = false,
		seismicsignature = 0,
		selfdestructas = "commanderExplosion",
		selfdestructcountdown = 5,
		showplayername = true,
		sightdistance = 450*(11/10)*(11/10),
		sonardistance = 450*(11/10)*(11/10),
		terraformspeed = 1500*(4/3)*(4/3),
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.825,
		turnrate = 1133,
		upright = true,
		workertime = 300*(4/3)*(4/3),
		buildoptions = {
			[1] = "corsolar",
			[2] = "coradvsol",
			[3] = "corwin",
			[4] = "corgeo",
			[5] = "cormstor",
			[6] = "corestor",
			[7] = "cormex",
			[8] = "corexp",
			[9] = "cormakr",
			[10] = "corlab",
			[11] = "coralab",
			[12] = "corvp",
			[13] = "coravp",
			[14] = "corap",
			[15] = "coraap",
			[16] = "corhp",
			[17] = "cornanotc",
			[18] = "coreyes",
			[19] = "corrad",
			[20] = "cordrag",
			[21] = "cormaw",
			[22] = "corllt",
			[23] = "corhllt",
			[24] = "corhlt",
			[25] = "corpun",
			[26] = "corrl",
			[27] = "cormadsam",
			[28] = "corerad",
			[29] = "cordl",
			[30] = "corjamt",
			[31] = "corsy",
			[32] = "corasy",
			[33] = "cortide",
			[34] = "coruwmex",
			[35] = "corfmkr",
			[36] = "coruwms",
			[37] = "coruwes",
			[38] = "corfhp",
			[39] = "coramsub",
			[40] = "corsonar",
			[41] = "corfrad",
			[42] = "corfdrag",
			[43] = "cortl",
			[44] = "corgplat",
			[45] = "corfrt",
			[46] = "corfhlt",
			[47] = "corplat",
			[48] = "seaplatform",
		},
		customparams = {
			--death_sounds = "commander",
			iscommander = true,
			paralyzemultiplier = 0.025,
			area_mex_def = "cormex",
			passiverepaireractive = 1,
			passiverepairerrange = 400,
			passiverepairerratio = 0.1,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "35 12 54",
				collisionvolumetype = "cylY",
				damage = 10000,
				description = "Commander Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = wreck_metal,
				object = "CORCOM_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 5000,
				description = "Commander Debris",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 1250,
				object = "2X2C",
                collisionvolumescales = "35.0 4.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			 pieceExplosionGenerators = { 
 				"deathceg3",
 				"deathceg4",
 			}, 
			explosiongenerators = {
				[1] = "custom:com_sea_laser_bubbles",
				[2] = "custom:barrelshot-medium",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			cloak = "kloak2",
			repair = "repair2",
			uncloak = "kloak2un",
			underattack = "warning2",
			unitcomplete = "kccorsel",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kcormov",
			},
			select = {
				[1] = "kccorsel",
			},
		},
		weapondefs = {
			arm_disintegrator = {
				areaofeffect = 36,
				avoidfeature = false,
				avoidfriendly = false,
				avoidground = false,
				commandfire = true,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				--waterbounce = true, -- weapon will stick to the surface
				groundbounce = true,
				bounceRebound = 0, --stick the explosion to ground with 0 vertical component
				waterweapon = true, --dgun can pass trough water
				firesubmersed = false, -- but not _fire_ underwater
				energypershot = 500*(7/6)*(7/6),
                cegTag = "dgunprojectile",
				explosiongenerator = "custom:expldgun",
				firestarter = 100,
				impulseboost = 0,
				impulsefactor = 0,
				name = "Disintegrator",
				noexplode = true,
				noselfdamage = true,
				range = 250*(7/6)*(7/6),
				reloadtime = 0.9,
				soundhit = "xplomas2",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "disigun1",
				soundtrigger = true,
				tolerance = 10000,
				turret = true,
				weapontimer = 4.2,
				weapontype = "DGun",
				weaponvelocity = 300*(4/3)*(4/3),
				damage = {
					default = 99999,
				},
			},
			armcomlaser = {
				areaofeffect = 12,
				avoidfeature = false,
				beamtime = 0.1,
				corethickness = 0.1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.99,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 70,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "J7Laser",
				noselfdamage = true,
				range = 475,
				reloadtime = 0.2,
				rgbcolor = "0.5 0.5 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "lasrfir1",
				soundtrigger = 1,
				targetmoveerror = 0.05,
				thickness = 2,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 900,
				damage = {
					bombers = 360,
					default = 150,
					fighters = 220,
					subs = 10,
				},
			},
			armcomsealaser = {
				areaofeffect = 12,
				avoidfeature = false,
				beamtime = 0.3,
				corethickness = 0.1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 1,
				--explosiongenerator = "custom:UW_LASER_BURN",
				explosiongenerator = "custom:laserhit-small-blue",
				firestarter = 35,
				firesubmersed = true,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 0.3,
				laserflaresize = 7,
				name = "J7NSLaser",
				noselfdamage = true,
				range = 260,
				reloadtime = 1,
				rgbcolor = "0.2 0.2 0.6",
				rgbcolor2 = "0.2 0.2 0.2",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "uwlasrfir1",
				soundtrigger = 1,
				targetmoveerror = 0.05,
				thickness = 5,
				tolerance = 10000,
				turret = true,
				waterweapon = true,
				weapontype = "BeamLaser",
				weaponvelocity = 900,
				damage = {
					default = 125*0.5,
					subs = 75*0.25,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARMCOMLASER",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "ARMCOMSEALASER",
			},
			[3] = {
				def = "ARM_DISINTEGRATOR",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
